### ISSUE TITLE
Precompiling at container build time

### ISSUE THREAD

**Issue by samcmill** [maleadt/julia-ngc#4]
It would be highly advantageous to precompile the CUDA packages when building the container image.  

The limitation seems to be that the `CUDAdrv` package requires the real CUDA driver.  It would be nice if it could be built against the CUDA stub library (the real library would be available at runtime).

**Comment by maleadt** [comment]
>  It would be nice if it could be built against the CUDA stub library (the real library would be available at runtime).

The problem is not that we require a (stub) library because we're linking, it's that we actually query the driver library for information, e.g., to conditionally enables or specializes functionality. Our library wrappers also embed the path to libraries so that we don't have to dlsym. Both are not straightforward to postpone, and/or would result in an even longer initial execution time that would resemble the current precompilation.

One possible solution is to enumerate all possible combination we specialize on, and allow to hard-code other information such as the library paths, but that doesn't seem worth it to me and would blow up container build time. Why can't you perform the precompilation behind the scenes as soon as the system node is known, and ship that version of the contain (or the precompilation cache) to the user?

**Comment by samcmill** [comment]
The system config is not known until the user starts the container.  I.e., it is not known when the user pulls the container, so there is no option to ship different precompiled bits to each user based on their specific system config.

I wonder whether it's possible to specify some reasonable default values when you get an invalid answer from the stub library?  For instance, assume the CUDA driver lib version is 8.x or 9.x if the return status of cuDriverGetVersion != 0, rather than asserting it must be 0.  Similarly for the compute capability, if the compute capability cannot be determined, build a fat binary with some reasonable set of defaults like sm_35, sm_60, and sm_70 (or ptxas).  

Why is it necessary to embed the path to the library in the wrapper?  With other programming languages, you can dynamically link with a (stub) library and then set LD_LIBRARY_PATH to load an alternative library at runtime - no need to dlsym.  Not sure whether this is possible or not with Julia.

I realize this is a bigger set of changes and not suggesting that it block the NGC container.

**Comment by maleadt** [comment]
> The system config is not known until the user starts the container. I.e., it is not known when the user pulls the container, so there is no option to ship different precompiled bits to each user based on their specific system config.

Yeah, I mistakenly thought there was a "run this on NVIDIA's cloud" option with NGC, where this would be viable. I know it isn't possible in general.
